### ISSUE TITLE
Removing Points on the Trajectory Input Causes an Error

### ISSUE THREAD

**Issue by Gugym** [MetOffice/qgis-plugin-edr#13]
QGIS3.28.6, Plugin version 0.13.1.

When trying to add a trajectory through the dialogue there are issues with inputting data points.

Steps to reproduce:
Open the QGIS Plugin and go to service: https://ogcie.iblsoft.com/edr, select collection GFS - Layer between two depths below land surface and an instance of the data before selecting the data query of trajectory. Add new points using the green + button, then try pressing the red - button and and the following error occurs.

An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'text' 
Traceback (most recent call last):
  File "C:\Users/guy.collins/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\edr_plugin\gui\query_tools.py", line 433, in update_geometry_wkt
    geom = self.query_geometry()
  File "C:\Users/guy.collins/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\edr_plugin\gui\query_tools.py", line 420, in query_geometry
    point = QgsPoint(self._cell_to_float(i, 0), self._cell_to_float(i, 1))
  File "C:\Users/guy.collins/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\edr_plugin\gui\query_tools.py", line 399, in _cell_to_float
    text = self.linestring_tw.cellWidget(row, col).text()
AttributeError: 'NoneType' object has no attribute 'text'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.6-Firenze Firenze, 868c9fa03b 

Python Path:
C:/PROGRA~1/QGIS32~1.6/apps/qgis-ltr/./python
C:/Users/guy.collins/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/guy.collins/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.6/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS32~1.6\apps\grass\grass82\etc\python
C:\Users\Default\Documents
C:\Program Files\QGIS 3.28.6\bin\python39.zip
C:\PROGRA~1\QGIS32~1.6\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib
C:\Program Files\QGIS 3.28.6\bin
C:\PROGRA~1\QGIS32~1.6\apps\Python39
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages\Pythonwin
C:/Users/guy.collins/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Temp
.

**Comment by Gugym** [comment]
It appears that for each digit entered in the z or y column the focus is then removed from the input box.
